#!/usr/bin/python3
import argparse

from tools.manifest.webservicemonitor import WebServiceMonitor

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Toolforge grid engine webservice watchdog',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        'legacy', metavar='LEGACY', nargs='*', help=argparse.SUPPRESS)
    parser.add_argument(
        '--sleep', metavar='N', type=int, default=60,
        help='Number of seconds to sleep between runs')
    args = parser.parse_args()

    with open('/etc/wmcs-project') as f:
        project_name = f.read().strip()

    collector = WebServiceMonitor(
        sleep=args.sleep,
    )
    collector.main()
